name: CI

on: [push]

jobs: 
  sast-scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Bandit
      run: pip install bandit
      
    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json
  
  image_scan:
     name: Build Image and Run Image scan
     runs-on: ubuntu-latest

     steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Setup Docker
       uses:  docker-practice/actions-setup-docker@v1
       with:
         docker_version: '20.10.7'

     - name: Build Docker image
       run: docker build -f Dockerfile -t myapp:latest .
     
          

    
  
